### ISSUE TITLE
Error installing HHVM

### ISSUE THREAD

**Issue by MikeBinstock** [lewg/docker-hhvm-pagespeed#1]
hi, maybe something is missing here. Not sure what.

"gpg: requesting key 1BE7A449 from hkp server keyserver.ubuntu.com
?: keyserver.ubuntu.com: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
ERROR: Service 'web' failed to build: The command '/bin/sh -c apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449' returned a non-zero code: 2"

**Comment by lewg** [comment]
Looks like there was an error on the ubuntu key server. I just ran the build with no issues. Does it consistently error out this way?

**Comment by MikeBinstock** [comment]
Now it is running well. Tks
